language: python

python:
  - "3.5"

branches:
  only:
    - master
    - develop

cache:
  pip: true

before_install:
  - pip install git+https://github.com/Rostlab/nalaf.git@feature/Experimental
  - python -m nalaf.download_corpora
  - pip install codecov

install:
  - pip install .
  - python3 -m relna.download_corpora

script:
  - nosetests --with-coverage
  - time python simple_evaluation.py --corpus relna

after_success:
  - codecov
